Repository RedHatInsights/topological_inventory-amazon, pull requests merged in 2020-02, with the labels that each got.

#51 If a source is configured only for cost don't mark it unavailable
  lib/topological_inventory/amazon/operations/source.rb
Labels: bug

#52 Move to UBI base image
  Dockerfile
Labels: enhancement

#54 Use the released version of ingress_api-client
  Gemfile
Labels: unmergeable
